import {useEffect,useState} from 'react';
import {IonApp,IonContent,IonPage,IonRefresher,IonRefresherContent,IonModal,IonToast,IonSkeletonText,IonTabBar,IonTabButton,IonLabel,setupIonicReact} from '@ionic/react';
import {Brand,Icon,IconName,Empty} from './components/UI';
import Home from './pages/Home';
import {Calendar,Attendance,Reports,Notices,Schedule,Agenda,Profile,More,Occurrences} from './pages/Academic';
import {PortalProvider,usePortal} from './services/portal';
import {clearSession} from './services/siga';
setupIonicReact({mode:'ios'});
const titles:Record<string,string>={home:'Início',calendar:'Calendário',attendance:'Frequência','report-card':'Boletim',occurrences:'Ocorrências',notices:'Informes',schedule:'Horários',agenda:'Agenda',olympics:'Topo do Saber',profile:'Perfil',more:'Mais',settings:'Configurações',about:'Sobre',notifications:'Notificações'};
const tabs:{route:string;icon:IconName;label:string}[]=[{route:'home',icon:'home',label:'Início'},{route:'calendar',icon:'calendar',label:'Calendário'},{route:'attendance',icon:'attendance',label:'Frequência'},{route:'report-card',icon:'report',label:'Boletim'},{route:'more',icon:'more',label:'Mais'}];
const READ_KEY='siga_portal_notice_read';
function Shell(){const {data,ready,reload}=usePortal();const [route,setRoute]=useState(()=>location.hash.slice(2)||'home'),[sheet,setSheet]=useState<{title:string;body:React.ReactNode}|null>(null),[toast,setToast]=useState(''),[read,setRead]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem(READ_KEY)||'[]')}catch{return []}}),[theme,setTheme]=useState(()=>localStorage.getItem('siga-theme')||'light'),[offline,setOffline]=useState(!navigator.onLine);
useEffect(()=>{const fn=()=>setRoute(location.hash.slice(2)||'home');window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[]);
useEffect(()=>{if(ready&&!data)location.replace('/login.html')},[ready,data]);
useEffect(()=>{const media=matchMedia('(prefers-color-scheme: dark)');const update=()=>document.documentElement.classList.toggle('dark',theme==='dark'||theme==='system'&&media.matches);update();media.addEventListener('change',update);localStorage.setItem('siga-theme',theme);return()=>media.removeEventListener('change',update)},[theme]);
useEffect(()=>{const on=()=>setOffline(!navigator.onLine);window.addEventListener('online',on);window.addEventListener('offline',on);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',on)}},[]);
function go(r:string){location.hash='/'+r;setRoute(r)}function detail(title:string,body:React.ReactNode){setSheet({title,body})}function markRead(id:string){setRead(prev=>{const next=prev.includes(id)?prev:[...prev,id];localStorage.setItem(READ_KEY,JSON.stringify(next));return next})}async function logout(){clearSession();location.replace('/login.html')}
if(!ready||!data)return <IonApp><IonSkeletonText animated style={{width:'100%',height:'100vh'}}/></IonApp>;
const notices=data.notices;const unread=notices.filter(n=>!read.includes(n.id)).length;const selected=tabs.some(t=>t.route===route)?route:'more';let content:React.ReactNode;
switch(route){case 'home':content=<Home go={go}/>;break;case 'calendar':content=<Calendar detail={detail}/>;break;case 'attendance':content=<Attendance detail={detail}/>;break;case 'report-card':content=<Reports detail={detail}/>;break;case 'occurrences':content=<Occurrences/>;break;case 'notices':content=<Notices read={read} onRead={markRead}/>;break;case 'schedule':content=<Schedule/>;break;case 'agenda':content=<Agenda/>;break;case 'profile':content=<Profile/>;break;case 'olympics':content=<section className="surface"><Empty title="Novas descobertas vêm por aí." description="Olimpíadas e projetos serão exibidos quando disponibilizados pela sua escola."/></section>;break;case 'settings':content=<section className="surface padded"><h2>Aparência</h2><p>Escolha o tema do aplicativo.</p><div className="theme-options">{[['light','Claro'],['dark','Escuro'],['system','Sistema']].map(([v,l])=><label key={v}><input type="radio" name="theme" checked={theme===v} onChange={()=>setTheme(v)}/>{l}</label>)}</div><h2>Instalar aplicativo</h2><p>Abra o menu do navegador e selecione “Instalar aplicativo” ou “Adicionar à Tela de Início”.</p></section>;break;case 'about':content=<section className="surface padded"><Brand/><h2>Uma jornada de futuro.</h2><p>Portal do Aluno · SIGA EDUCA</p><p>Versão 1.0</p></section>;break;case 'notifications':content=<section className="surface">{notices.length?notices.map(n=><button key={n.id} className="notification-row" onClick={()=>{markRead(n.id);go('notices')}}><div className="icon-box purple"><Icon name="notices"/></div><div><h3>{n.title}</h3><p>{read.includes(n.id)?'Visualizado':'Novo informe'}</p></div><Icon name="next"/></button>):<Empty title="Nenhuma notificação."/>}</section>;break;default:content=<More go={go} logout={logout}/>}
return <IonApp><div className="app-viewport">{<IonPage><header className="app-header">{route==='home'?<><button aria-label="Abrir menu" onClick={()=>go('more')}><Icon name="menu"/></button><Brand/><button className="bell" aria-label="Notificações" onClick={()=>go('notifications')}><Icon name="notifications"/>{unread>0&&<span>{unread}</span>}</button><button className="profile-button" aria-label="Meu perfil" onClick={()=>go('profile')}>{data.student.avatarUrl?<img src={data.student.avatarUrl} alt=""/>:<Icon name="profile"/>}</button></>:<><button aria-label="Voltar ao início" onClick={()=>go('home')}><Icon name="back"/></button><h1>{titles[route]||'Mais'}</h1><button aria-label="Notificações" onClick={()=>go('notifications')}><Icon name="notifications"/></button></>}</header>{offline&&<div className="offline">Sem conexão · Os dados da escola podem estar desatualizados</div>}<IonContent><IonRefresher slot="fixed" onIonRefresh={e=>{reload().finally(()=>{setToast('Portal atualizado');e.detail.complete()})}}><IonRefresherContent pullingText="Puxe para atualizar"/></IonRefresher><main key={route} className={'page '+(route==='home'?'home-page':'')}>{content}</main></IonContent><IonTabBar selectedTab={selected}>{tabs.map(t=><IonTabButton key={t.route} tab={t.route} selected={selected===t.route} onClick={()=>go(t.route)}><Icon name={t.icon}/><IonLabel>{t.label}</IonLabel></IonTabButton>)}</IonTabBar></IonPage>}</div><IonModal isOpen={!!sheet} onDidDismiss={()=>setSheet(null)} initialBreakpoint={0.8} breakpoints={[0,0.8,1]}><div className="sheet"><header><h2>{sheet?.title}</h2><button aria-label="Fechar" onClick={()=>setSheet(null)}><Icon name="close"/></button></header>{sheet?.body}</div></IonModal><IonToast isOpen={!!toast} message={toast} duration={2200} onDidDismiss={()=>setToast('')}/></IonApp>}
export default function App(){return <PortalProvider><Shell/></PortalProvider>}
