import {useEffect,useState} from 'react';
import {Icon,Ring,Empty} from '../components/UI';
import {usePortal} from '../services/portal';
import {loadAttendanceYear,openReport,type AttendanceSummary,type SchoolEvent} from '../services/siga';
import {Navigate} from './Home';
const fmt=(value:string)=>new Date(value+'T12:00:00').toLocaleDateString('pt-BR',{day:'numeric',month:'long'});
const monthTag=(value:string)=>new Date(value+'T12:00:00').toLocaleDateString('pt-BR',{month:'short'}).replace('.','');
export function Calendar({detail}:{detail:(title:string,body:React.ReactNode)=>void}){const {data}=usePortal();const events=data?.events||[];const [date,setDate]=useState(()=>new Date());const year=date.getFullYear(),month=date.getMonth(),days=new Date(year,month+1,0).getDate(),start=new Date(year,month,1).getDay();const upcoming=events.filter(e=>e.date>=new Date().toISOString().slice(0,10)).slice(0,8);return <div className="calendar-layout"><section className="surface calendar"><div className="selector"><button aria-label="Mês anterior" onClick={()=>setDate(new Date(year,month-1,1))}><Icon name="back"/></button><strong>{date.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</strong><button aria-label="Próximo mês" onClick={()=>setDate(new Date(year,month+1,1))}><Icon name="next"/></button></div><div className="calendar-grid">{['DOM','SEG','TER','QUA','QUI','SEX','SÁB'].map(d=><small key={d}>{d}</small>)}{Array.from({length:start},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:days},(_,i)=>{const d=i+1,key=`${year}-${String(month+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,dayEvents=events.filter(e=>e.date===key);return <button key={d} className={`${d===date.getDate()?'selected':''} ${dayEvents.length?'has-event':''}`} onClick={()=>{setDate(new Date(year,month,d));detail(fmt(key),dayEvents.length?<EventList items={dayEvents}/>:<Empty title="Nenhum evento nesta data." description="Consulte outras datas no calendário escolar."/>)}}>{d}{dayEvents.length>0&&<i/>}</button>})}</div><div className="legend"><span><i/>Evento escolar</span><span><i/>Data selecionada</span></div></section><section className="surface padded"><h2>Próximas datas</h2><p className="muted">Datas importantes para sua jornada.</p>{upcoming.length?<EventList items={upcoming}/>:<Empty title="Nenhum evento no calendário." description="A escola ainda não publicou datas para a sua turma."/>}</section></div>}
export function EventList({items}:{items:SchoolEvent[]}){return <div>{items.map(e=><article className="event-row" key={e.id}><span className="date-box"><b>{e.date.slice(-2)}</b>{monthTag(e.date)}</span><div><span className="eyeline">{e.category}{e.date?` · ${fmt(e.date)}`:''}</span><h3>{e.title}</h3>{e.time&&<p>{e.time}</p>}{e.description&&<p>{e.description}</p>}</div></article>)}</div>}
export function Attendance({detail}:{detail:(title:string,body:React.ReactNode)=>void}){const {data}=usePortal();const [year,setYear]=useState(new Date().getFullYear());const [stats,setStats]=useState<AttendanceSummary|null>(data?.attendance||null);useEffect(()=>{if(!data)return;if(year===new Date().getFullYear()){setStats(data.attendance);return}let on=true;loadAttendanceYear(data.student,year).then(next=>{if(on)setStats(next)});return()=>{on=false}},[year,data]);if(!stats)return null;return <div className="narrow"><Year value={year} set={setYear}/>{stats.total===0?<Empty title="Frequência indisponível para este ano." description="As aulas e as faltas aparecem quando a escola registra o calendário e a chamada."/>:<><section className="surface padded attendance"><Ring value={stats.percentage}/><div className="stats"><div><b>{stats.present}</b><span>Presenças</span></div><div><b>{stats.absent}</b><span>Faltas</span></div><div><b>{stats.justified}</b><span>Justificadas</span></div></div><div className="total">Total de aulas <b>{stats.total}</b></div></section>{stats.history.length>0&&<><h2 className="section-title">Histórico</h2><section className="surface">{stats.history.map(m=><button className="list-row" key={m.key} onClick={()=>detail(`Frequência · ${m.label}`,<><Ring value={m.value}/><div className="stats"><div><b>{m.present}</b><span>Presenças</span></div><div><b>{m.absent}</b><span>Faltas</span></div><div><b>{m.justified}</b><span>Justificadas</span></div></div></>)}><b>{m.label}</b><span>{m.value}%</span><Icon name="next"/></button>)}</section></>}</>}</div>}
function Year({value,set}:{value:number;set:(n:number)=>void}){return <div className="selector surface"><button aria-label="Ano anterior" onClick={()=>set(value-1)}><Icon name="back"/></button><b>Ano letivo {value}</b><button aria-label="Próximo ano" onClick={()=>set(value+1)}><Icon name="next"/></button></div>}
export function Reports({detail}:{detail:(title:string,body:React.ReactNode)=>void}){const {data}=usePortal();const [year,setYear]=useState(new Date().getFullYear());const reports=(data?.reports||[]).filter(r=>r.ano===year);return <div className="narrow"><Year value={year} set={setYear}/>{year!==new Date().getFullYear()?<Empty title="Nenhum boletim para este ano."/>:(data?.reports||[]).map(n=><button className="surface report-item" key={n.bimestre} onClick={()=>{if(n.published&&n.id){openReport(n.id).then(ok=>{if(!ok)detail(`${n.bimestre}º Bimestre`,<Empty title="PDF oficial não encontrado neste aparelho." description="O boletim publicado fica disponível no navegador em que a escola gerou o arquivo."/>)});return}detail(`${n.bimestre}º Bimestre`,<Empty title="Seu boletim ainda não foi publicado." description="Os boletins oficiais são disponibilizados pela escola."/>)}}><div className={`icon-box ${n.published?'green':'gray'}`}><Icon name="report"/></div><div><h3>{n.bimestre}º Bimestre</h3><span className={`badge ${n.published?'green':'red'}`}>{n.published?'Publicado':'Não publicado'}</span><p>{n.fileName|| (n.published?'Toque para abrir o PDF':'Em processamento')}</p></div><Icon name="next"/></button>)}{!reports.length&&year===new Date().getFullYear()&&<div className="info"><Icon name="about"/>Os boletins serão exibidos assim que forem disponibilizados pela sua escola.</div>}</div>}
export function Notices({read,onRead}:{read:string[];onRead:(id:string)=>void}){const {data}=usePortal();const notices=data?.notices||[];if(!notices.length)return <Empty title="Nenhum informe no momento." description="Os comunicados da escola aparecerão aqui."/>;return <div className="notice-list">{notices.map(n=><article className="surface padded" key={n.id}><div className="notice-meta"><span>{fmt(n.date)}</span><span className={`badge ${read.includes(n.id)?'gray':'purple'}`}>{read.includes(n.id)?'Lido':'Novo'}</span></div><h2>{n.title}</h2><p>{n.content}</p><button className="text-button" disabled={read.includes(n.id)} onClick={()=>onRead(n.id)}><Icon name="check"/>{read.includes(n.id)?'Informe lido':'Marcar como lido'}</button></article>)}</div>}
export function Occurrences(){const {data}=usePortal();const list=data?.occurrences||[];if(!list.length)return <section className="surface"><Empty title="Nenhuma ocorrência registrada." description="Seus registros e acompanhamentos aparecerão aqui."/></section>;return <section className="surface">{list.map(o=><article className="list-row" key={o.id}><div><b>{o.tipo}</b><p>{o.descricao||o.status}</p><small>{o.data?fmt(o.data):''} · {o.status}</small></div></article>)}</section>}
export function Schedule(){return <div className="narrow"><Empty title="Horários ainda não publicados." description="A grade da turma aparece aqui quando a escola disponibilizar os horários."/></div>}
export function Agenda(){const {data}=usePortal();const [filter,setFilter]=useState('Todos');const items=data?.agenda||[];const categories=['Todos',...Array.from(new Set(items.map(e=>e.category)))];const visible=items.filter(e=>filter==='Todos'||e.category===filter);return <><div className="day-tabs">{categories.map(f=><button className={filter===f?'active':''} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div><section className="surface padded">{visible.length?<EventList items={visible}/>:<Empty title="Nenhuma atividade na agenda." description="Provas, reuniões e eventos da sua turma aparecerão aqui."/>}</section></>}
export function Profile(){const {data}=usePortal();if(!data)return null;const {student}=data;return <section className="surface padded narrow profile"><div className="avatar">{student.avatarUrl?<img src={student.avatarUrl} alt=""/>:studentInitials(student.name)}</div><h2>{student.name}</h2><p>Estudante</p>{[['E-mail institucional',student.email],['Série',student.grade],['Turma',student.className],['Turno',student.shift],['Escola',student.school]].filter(([,v])=>v).map(([k,v])=><div className="profile-field" key={k}><small>{k}</small><b>{v}</b></div>)}</section>}
function studentInitials(name:string){const parts=name.trim().split(/\s+/).filter(Boolean);return ((parts[0]?.[0]||'A')+(parts.length>1?parts[parts.length-1][0]:'')).toUpperCase()}
export function More({go,logout}:{go:Navigate;logout:()=>void}){return <section className="surface narrow">{[['profile','Perfil'],['schedule','Horários'],['agenda','Agenda'],['olympics','Topo do Saber'],['notices','Informes'],['settings','Configurações'],['about','Sobre']].map(([route,title])=><button className="list-row" key={route} onClick={()=>go(route)}><b>{title}</b><Icon name="next"/></button>)}<button className="list-row danger" onClick={logout}><b>Sair</b><Icon name="logout"/></button></section>}
