import {useEffect,useState} from 'react';
import {Icon,Ring,Empty} from '../components/UI';
import {usePortal} from '../services/portal';
import {clearSession,fetchReportFile,loadAttendanceYear,openYoutube,youtubeId,type AttendanceSummary,type Notice,type SchoolEvent} from '../services/siga';
import {Navigate} from './Home';
const fmt=(value:string)=>new Date(value+'T12:00:00').toLocaleDateString('pt-BR',{day:'numeric',month:'long'});
const monthTag=(value:string)=>new Date(value+'T12:00:00').toLocaleDateString('pt-BR',{month:'short'}).replace('.','');
export function Calendar({detail,events:given}:{detail:(title:string,body:React.ReactNode)=>void;events?:SchoolEvent[]}){const {data}=usePortal();const events=given||data?.events||[];const [date,setDate]=useState(()=>new Date());const year=date.getFullYear(),month=date.getMonth(),days=new Date(year,month+1,0).getDate(),start=new Date(year,month,1).getDay();const upcoming=events.filter(e=>e.date>=new Date().toISOString().slice(0,10)).slice(0,8);return <div className="calendar-layout"><section className="surface calendar"><div className="selector"><button aria-label="Mês anterior" onClick={()=>setDate(new Date(year,month-1,1))}><Icon name="back"/></button><strong>{date.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</strong><button aria-label="Próximo mês" onClick={()=>setDate(new Date(year,month+1,1))}><Icon name="next"/></button></div><div className="calendar-grid">{['DOM','SEG','TER','QUA','QUI','SEX','SÁB'].map(d=><small key={d}>{d}</small>)}{Array.from({length:start},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:days},(_,i)=>{const d=i+1,key=`${year}-${String(month+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,dayEvents=events.filter(e=>e.date===key);return <button key={d} className={`${d===date.getDate()?'selected':''} ${dayEvents.length?'has-event':''}`} onClick={()=>{setDate(new Date(year,month,d));detail(fmt(key),dayEvents.length?<EventList items={dayEvents}/>:<Empty title="Nenhum evento nesta data." description="Consulte outras datas no calendário escolar."/>)}}>{d}{dayEvents.length>0&&<i/>}</button>})}</div><div className="legend"><span><i/>Evento escolar</span><span><i/>Data selecionada</span></div></section><section className="surface padded"><h2>Próximas datas</h2><p className="muted">Datas importantes para sua jornada.</p>{upcoming.length?<EventList items={upcoming}/>:<Empty title="Nenhum evento no calendário." description="A escola ainda não publicou datas para a sua turma."/>}</section></div>}
export function EventList({items}:{items:SchoolEvent[]}){return <div>{items.map(e=><article className="event-row" key={e.id}><span className="date-box"><b>{e.date.slice(-2)}</b>{monthTag(e.date)}</span><div><span className="eyeline">{e.category}{e.date?` · ${fmt(e.date)}`:''}</span><h3>{e.title}</h3>{e.time&&<p>{e.time}</p>}{e.description&&<p>{e.description}</p>}</div></article>)}</div>}
function phaseTone(code:string|null){if(code==='P')return 'green';if(code==='F')return 'red';if(code==='FJ')return 'amber';return 'gray'}
function emptyDay(date:string){const blank={code:null as string|null,label:'Sem registro',time:null as string|null};return {date,entrada:blank,saida:{...blank},consolidado:{code:null as string|null,label:'Pendente',time:null as string|null}}}
function studentCallMessage(day:{entrada:{code:string|null};saida:{code:string|null}}){if(!day.entrada.code)return {done:false,text:'A chamada de entrada ainda não foi realizada.'};if(!day.saida.code)return {done:false,text:'A chamada de entrada foi realizada. A saída ainda não foi feita.'};return {done:true,text:'A chamada de entrada e de saída foi realizada.'}}
export function Attendance({detail}:{detail:(title:string,body:React.ReactNode)=>void}){const {data}=usePortal();const [year,setYear]=useState(new Date().getFullYear());const [day,setDay]=useState(()=>{const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`});const [stats,setStats]=useState<AttendanceSummary|null>(data?.attendance||null);useEffect(()=>{if(!data)return;if(year===new Date().getFullYear()){setStats(data.attendance);return}let on=true;loadAttendanceYear(data.student,year).then(next=>{if(on)setStats(next)});return()=>{on=false}},[year,data]);if(!stats)return null;const selected=(stats.days||[]).find(item=>item.date===day)||emptyDay(day);const changeYear=(next:number)=>{setYear(next);setDay(current=>current.startsWith(String(next))?current:`${next}-01-01`)};return <div className="narrow"><Year value={year} set={changeYear}/>{stats.total>0&&<section className="surface padded attendance"><Ring value={stats.percentage}/><div className="stats"><div><b>{stats.present}</b><span>Presenças</span></div><div><b>{stats.absent}</b><span>Faltas</span></div><div><b>{stats.justified}</b><span>Justificadas</span></div></div><div className="total">Total de aulas <b>{stats.total}</b></div></section>}<label className="date-filter surface"><span>Data da chamada</span><input type="date" value={day} onChange={event=>{const value=event.target.value;if(!value)return;setDay(value);const next=Number(value.slice(0,4));if(next&&next!==year)setYear(next)}}/></label><article className="surface call-day"><h3>{fmt(day)}</h3><p className={studentCallMessage(selected).done?'call-done':'call-wait'}>{studentCallMessage(selected).text}</p>{([['Entrada',selected.entrada],['Saída',selected.saida],['Dia consolidado',selected.consolidado]] as const).map(([name,phase])=><div className="call-phase" key={name}><span>{name}</span><b className={`badge ${phaseTone(phase.code)}`}>{phase.label}{phase.time?` · ${phase.time}`:''}</b></div>)}</article>{stats.history.length>0&&<><h2 className="section-title">Histórico</h2><section className="surface">{stats.history.map(m=><button className="list-row" key={m.key} onClick={()=>detail(`Frequência · ${m.label}`,<><Ring value={m.value}/><div className="stats"><div><b>{m.present}</b><span>Presenças</span></div><div><b>{m.absent}</b><span>Faltas</span></div><div><b>{m.justified}</b><span>Justificadas</span></div></div></>)}><b>{m.label}</b><span>{m.value}%</span><Icon name="next"/></button>)}</section></>}</div>}
function Year({value,set}:{value:number;set:(n:number)=>void}){return <div className="selector surface"><button aria-label="Ano anterior" onClick={()=>set(value-1)}><Icon name="back"/></button><b>Ano letivo {value}</b><button aria-label="Próximo ano" onClick={()=>set(value+1)}><Icon name="next"/></button></div>}
const REPORT_YEAR=2026;
export function Reports({detail}:{detail:(title:string,body:React.ReactNode)=>void}){
  const {data}=usePortal();
  const reports=(data?.reports||[]).filter(item=>item.ano===REPORT_YEAR&&item.published&&item.id);
  const key=reports.map(item=>item.id).join('|');
  const [files,setFiles]=useState<Record<string,{url:string;name:string}>>({});
  const [failed,setFailed]=useState(false);
  useEffect(()=>{
    let alive=true;
    const created:string[]=[];
    if(!key){setFiles({});setFailed(false);return}
    setFailed(false);
    Promise.all(reports.map(async item=>{
      const file=await fetchReportFile(String(item.id));
      if(!file)return null;
      const url=URL.createObjectURL(file.blob);
      created.push(url);
      return [String(item.id),{url,name:item.fileName||'Boletim.pdf'}] as const;
    })).then(rows=>{
      if(!alive){created.forEach(url=>URL.revokeObjectURL(url));return}
      const next:Record<string,{url:string;name:string}>={};
      rows.forEach(row=>{if(row)next[row[0]]=row[1]});
      setFiles(next);
      setFailed(!Object.keys(next).length);
    });
    return()=>{alive=false;created.forEach(url=>URL.revokeObjectURL(url))};
  },[key]);
  if(!data?.portalLive&&!reports.length)return <div className="narrow"><div className="selector surface year-lock"><b>Ano letivo 2026</b></div><section className="surface padded"><Empty title="Entre novamente para ver o boletim." description="O arquivo publicado pela escola aparece depois do acesso do aluno."/><button className="text-button" onClick={()=>{clearSession();location.replace('/login.html')}}>Entrar novamente</button></section></div>;
  if(!reports.length)return <div className="narrow"><div className="selector surface year-lock"><b>Ano letivo 2026</b></div><section className="surface report-card"><div className="icon-box gray"><Icon name="report"/></div><div><h3>Boletim</h3><span className="badge red">Não publicado</span><p>Aguardando a escola</p></div></section><div className="info"><Icon name="about"/>O boletim de 2026 aparece aqui quando a escola publicar.</div></div>;
  return <div className="narrow"><div className="selector surface year-lock"><b>Ano letivo 2026</b></div>{reports.map(item=>{
    const title=item.label||'Boletim';
    const file=item.id?files[item.id]:undefined;
    return <article className="surface report-card" key={item.id}><div className="icon-box green"><Icon name="report"/></div><div><h3>{title}</h3><span className="badge green">Publicado</span><p>{item.fileName||'Boletim.pdf'}</p><div className="report-actions">{file?<><a className="view" href={file.url} target="_blank" rel="noopener noreferrer">Ver</a><a className="download" href={file.url} download={file.name}>Baixar</a></>:<button type="button" disabled>{failed?'Não foi possível abrir':'Preparando arquivo...'}</button>}</div></div></article>;
  })}{failed&&<div className="info"><Icon name="about"/>Não foi possível abrir o arquivo. Puxe a tela para atualizar ou entre novamente.</div>}</div>;
}

function noticeImage(n:Notice){return n.image?<img className="notice-image" src={n.image} alt=""/>:null}
export function Notices({read,onRead,items}:{read:string[];onRead:(id:string)=>void;items?:Notice[]}){const {data}=usePortal();const notices=items||data?.notices||[];if(!notices.length)return <Empty title="Nenhum informe no momento." description="Os comunicados da escola aparecerão aqui."/>;return <div className="notice-list">{notices.map(n=>{const imageFirst=n.layout==='imagem_texto';return <article className="surface padded" key={n.id}><div className="notice-meta"><span>{fmt(n.date)}</span><span className={`badge ${read.includes(n.id)?'gray':'purple'}`}>{read.includes(n.id)?'Lido':'Novo'}</span></div><h2>{n.title}</h2>{imageFirst&&noticeImage(n)}{n.content?<p className="notice-text">{n.content}</p>:null}{!imageFirst&&noticeImage(n)}<button className="text-button" disabled={read.includes(n.id)} onClick={()=>onRead(n.id)}><Icon name="check"/>{read.includes(n.id)?'Informe lido':'Marcar como lido'}</button></article>})}</div>}
export function Occurrences(){const {data}=usePortal();const list=data?.occurrences||[];if(!list.length)return <section className="surface"><Empty title="Nenhuma ocorrência registrada." description="Seus registros e acompanhamentos aparecerão aqui."/></section>;return <section className="surface">{list.map(o=><article className="list-row" key={o.id}><div><b>{o.tipo}</b><p>{o.descricao||o.status}</p><small>{o.data?fmt(o.data):''} · {o.status}</small></div></article>)}</section>}
const SCHEDULE_DRIVE_URL='https://drive.google.com/drive/folders/139yVJOFPzcaIfSxRuaK8MI22-W5OHpxI';
export function Schedule(){return <div className="narrow"><a className="surface schedule-card" href={SCHEDULE_DRIVE_URL} target="_blank" rel="noopener noreferrer"><div className="icon-box blue"><Icon name="schedule"/></div><div><h3>Horário de Aula</h3><p>Toque para abrir a grade no Drive.</p></div><Icon name="next"/></a></div>}
export function Agenda(){const {data}=usePortal();const [filter,setFilter]=useState('Todos');const items=data?.agenda||[];const categories=['Todos',...Array.from(new Set(items.map(e=>e.category)))];const visible=items.filter(e=>filter==='Todos'||e.category===filter);return <><div className="day-tabs">{categories.map(f=><button className={filter===f?'active':''} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div><section className="surface padded">{visible.length?<EventList items={visible}/>:<Empty title="Nenhuma atividade na agenda." description="Provas, reuniões e eventos da sua turma aparecerão aqui."/>}</section></>}
export function Profile(){const {data}=usePortal();if(!data)return null;const {student}=data;return <section className="surface padded narrow profile"><div className="avatar">{student.avatarUrl?<img src={student.avatarUrl} alt=""/>:studentInitials(student.name)}</div><h2>{student.name}</h2><p>Estudante</p>{[['E-mail institucional',student.email],['Série',student.grade],['Turma',student.className],['Turno',student.shift],['Escola',student.school]].filter(([,v])=>v).map(([k,v])=><div className="profile-field" key={k}><small>{k}</small><b>{v}</b></div>)}</section>}
function studentInitials(name:string){const parts=name.trim().split(/\s+/).filter(Boolean);return ((parts[0]?.[0]||'A')+(parts.length>1?parts[parts.length-1][0]:'')).toUpperCase()}
export function EnemDigital(){const {data}=usePortal();const lessons=data?.lessons||[];const [open,setOpen]=useState('');if(!lessons.length)return <Empty title="Nenhuma aula publicada." description="Quando a escola incluir o link do YouTube em Informativos, a aula aparece aqui."/>;return <div className="notice-list">{lessons.map(lesson=>{const shown=open===lesson.id;const tipo=lesson.displayType==='dropdown'?'dropdown':'card';const id=youtubeId(lesson.videoUrl);const watch=id?`https://www.youtube.com/watch?v=${id}`:'';return <article className={`lesson-item ${tipo}`} key={lesson.id}><button className="lesson-toggle" onClick={()=>setOpen(shown?'':lesson.id)}><h2>{lesson.title}</h2><span className="lesson-caret" aria-hidden="true">{shown?'▴':'▾'}</span></button>{shown&&<div className="lesson-body">{lesson.lessonData?<p className="notice-text">{lesson.lessonData}</p>:null}{lesson.content?<p className="notice-text">{lesson.content}</p>:null}{watch?<a className="lesson-youtube" href={watch} onClick={event=>{event.preventDefault();openYoutube(lesson.videoUrl)}}><img src={`https://i.ytimg.com/vi/${id}/hqdefault.jpg`} alt=""/><span>Assistir no YouTube</span></a>:<p>O link informado não é um vídeo do YouTube.</p>}</div>}</article>})}</div>}
export function More({go,logout}:{go:Navigate;logout:()=>void}){return <section className="surface narrow">{[['profile','Perfil'],['enem','Enem Pará Digital'],['schedule','Horários'],['agenda','Agenda'],['olympics','Topo do Saber'],['notices','Informes'],['settings','Configurações'],['about','Sobre']].map(([route,title])=><button className="list-row" key={route} onClick={()=>go(route)}><b>{title}</b><Icon name="next"/></button>)}<button className="list-row danger" onClick={logout}><b>Sair</b><Icon name="logout"/></button></section>}
