import {useEffect,useState} from 'react';
import {Icon,Ring,Empty} from '../components/UI';
import {usePortal} from '../services/portal';
import {loadAttendanceYear,openReport,type AttendanceSummary,type Notice,type SchoolEvent} from '../services/siga';
import {Navigate} from './Home';
const fmt=(value:string)=>new Date(value+'T12:00:00').toLocaleDateString('pt-BR',{day:'numeric',month:'long'});
const monthTag=(value:string)=>new Date(value+'T12:00:00').toLocaleDateString('pt-BR',{month:'short'}).replace('.','');
export function Calendar({detail,events:given}:{detail:(title:string,body:React.ReactNode)=>void;events?:SchoolEvent[]}){const {data}=usePortal();const events=given||data?.events||[];const [date,setDate]=useState(()=>new Date());const year=date.getFullYear(),month=date.getMonth(),days=new Date(year,month+1,0).getDate(),start=new Date(year,month,1).getDay();const upcoming=events.filter(e=>e.date>=new Date().toISOString().slice(0,10)).slice(0,8);return <div className="calendar-layout"><section className="surface calendar"><div className="selector"><button aria-label="Mês anterior" onClick={()=>setDate(new Date(year,month-1,1))}><Icon name="back"/></button><strong>{date.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</strong><button aria-label="Próximo mês" onClick={()=>setDate(new Date(year,month+1,1))}><Icon name="next"/></button></div><div className="calendar-grid">{['DOM','SEG','TER','QUA','QUI','SEX','SÁB'].map(d=><small key={d}>{d}</small>)}{Array.from({length:start},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:days},(_,i)=>{const d=i+1,key=`${year}-${String(month+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,dayEvents=events.filter(e=>e.date===key);return <button key={d} className={`${d===date.getDate()?'selected':''} ${dayEvents.length?'has-event':''}`} onClick={()=>{setDate(new Date(year,month,d));detail(fmt(key),dayEvents.length?<EventList items={dayEvents}/>:<Empty title="Nenhum evento nesta data." description="Consulte outras datas no calendário escolar."/>)}}>{d}{dayEvents.length>0&&<i/>}</button>})}</div><div className="legend"><span><i/>Evento escolar</span><span><i/>Data selecionada</span></div></section><section className="surface padded"><h2>Próximas datas</h2><p className="muted">Datas importantes para sua jornada.</p>{upcoming.length?<EventList items={upcoming}/>:<Empty title="Nenhum evento no calendário." description="A escola ainda não publicou datas para a sua turma."/>}</section></div>}
export function EventList({items}:{items:SchoolEvent[]}){return <div>{items.map(e=><article className="event-row" key={e.id}><span className="date-box"><b>{e.date.slice(-2)}</b>{monthTag(e.date)}</span><div><span className="eyeline">{e.category}{e.date?` · ${fmt(e.date)}`:''}</span><h3>{e.title}</h3>{e.time&&<p>{e.time}</p>}{e.description&&<p>{e.description}</p>}</div></article>)}</div>}
function phaseTone(code:string|null){if(code==='P')return 'green';if(code==='F')return 'red';if(code==='FJ')return 'amber';return 'gray'}
function emptyDay(date:string){const blank={code:null as string|null,label:'Sem registro',time:null as string|null};return {date,entrada:blank,saida:{...blank},consolidado:{code:null as string|null,label:'Pendente',time:null as string|null}}}
export function Attendance({detail}:{detail:(title:string,body:React.ReactNode)=>void}){const {data}=usePortal();const [year,setYear]=useState(new Date().getFullYear());const [day,setDay]=useState(()=>{const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`});const [stats,setStats]=useState<AttendanceSummary|null>(data?.attendance||null);useEffect(()=>{if(!data)return;if(year===new Date().getFullYear()){setStats(data.attendance);return}let on=true;loadAttendanceYear(data.student,year).then(next=>{if(on)setStats(next)});return()=>{on=false}},[year,data]);if(!stats)return null;const selected=(stats.days||[]).find(item=>item.date===day)||emptyDay(day);const changeYear=(next:number)=>{setYear(next);setDay(current=>current.startsWith(String(next))?current:`${next}-01-01`)};return <div className="narrow"><Year value={year} set={changeYear}/>{stats.total>0&&<section className="surface padded attendance"><Ring value={stats.percentage}/><div className="stats"><div><b>{stats.present}</b><span>Presenças</span></div><div><b>{stats.absent}</b><span>Faltas</span></div><div><b>{stats.justified}</b><span>Justificadas</span></div></div><div className="total">Total de aulas <b>{stats.total}</b></div></section>}<label className="date-filter surface"><span>Data da chamada</span><input type="date" value={day} onChange={event=>{const value=event.target.value;if(!value)return;setDay(value);const next=Number(value.slice(0,4));if(next&&next!==year)setYear(next)}}/></label><article className="surface call-day"><h3>{fmt(day)}</h3>{([['Entrada',selected.entrada],['Saída',selected.saida],['Dia consolidado',selected.consolidado]] as const).map(([name,phase])=><div className="call-phase" key={name}><span>{name}</span><b className={`badge ${phaseTone(phase.code)}`}>{phase.label}{phase.time?` · ${phase.time}`:''}</b></div>)}</article>{stats.history.length>0&&<><h2 className="section-title">Histórico</h2><section className="surface">{stats.history.map(m=><button className="list-row" key={m.key} onClick={()=>detail(`Frequência · ${m.label}`,<><Ring value={m.value}/><div className="stats"><div><b>{m.present}</b><span>Presenças</span></div><div><b>{m.absent}</b><span>Faltas</span></div><div><b>{m.justified}</b><span>Justificadas</span></div></div></>)}><b>{m.label}</b><span>{m.value}%</span><Icon name="next"/></button>)}</section></>}</div>}
function Year({value,set}:{value:number;set:(n:number)=>void}){return <div className="selector surface"><button aria-label="Ano anterior" onClick={()=>set(value-1)}><Icon name="back"/></button><b>Ano letivo {value}</b><button aria-label="Próximo ano" onClick={()=>set(value+1)}><Icon name="next"/></button></div>}
const REPORT_YEAR=2026;
export function Reports({detail}:{detail:(title:string,body:React.ReactNode)=>void}){const {data}=usePortal();const reports=(data?.reports||[]).filter(r=>r.ano===REPORT_YEAR);const items=reports.length?reports:[{bimestre:0,label:'Boletim',ano:REPORT_YEAR,published:false,id:undefined as string|undefined,fileName:undefined as string|undefined}];return <div className="narrow"><div className="selector surface year-lock"><b>Ano letivo 2026</b></div>{items.map(n=>{const title=n.label||'Boletim';return <button className="surface report-item" key={n.id||title} onClick={()=>{if(n.published&&n.id){openReport(n.id).then(ok=>{if(!ok)detail(title,<Empty title="Não foi possível abrir o boletim." description="Peça à escola para publicar o arquivo novamente."/>)});return}detail(title,<Empty title="Seu boletim ainda não foi publicado." description="O boletim oficial aparece aqui quando a escola enviar."/>)}}><div className={`icon-box ${n.published?'green':'gray'}`}><Icon name="report"/></div><div><h3>{title}</h3><span className={`badge ${n.published?'green':'red'}`}>{n.published?'Publicado':'Não publicado'}</span><p>{n.fileName|| (n.published?'Toque para abrir o PDF':'Aguardando a escola')}</p></div><Icon name="next"/></button>})}<div className="info"><Icon name="about"/>Boletim do ano letivo de 2026, quando a escola publicar.</div></div>}
export function Notices({read,onRead,items}:{read:string[];onRead:(id:string)=>void;items?:Notice[]}){const {data}=usePortal();const notices=items||data?.notices||[];if(!notices.length)return <Empty title="Nenhum informe no momento." description="Os comunicados da escola aparecerão aqui."/>;return <div className="notice-list">{notices.map(n=><article className="surface padded" key={n.id}><div className="notice-meta"><span>{fmt(n.date)}</span><span className={`badge ${read.includes(n.id)?'gray':'purple'}`}>{read.includes(n.id)?'Lido':'Novo'}</span></div><h2>{n.title}</h2><p>{n.content}</p><button className="text-button" disabled={read.includes(n.id)} onClick={()=>onRead(n.id)}><Icon name="check"/>{read.includes(n.id)?'Informe lido':'Marcar como lido'}</button></article>)}</div>}
export function Occurrences(){const {data}=usePortal();const list=data?.occurrences||[];if(!list.length)return <section className="surface"><Empty title="Nenhuma ocorrência registrada." description="Seus registros e acompanhamentos aparecerão aqui."/></section>;return <section className="surface">{list.map(o=><article className="list-row" key={o.id}><div><b>{o.tipo}</b><p>{o.descricao||o.status}</p><small>{o.data?fmt(o.data):''} · {o.status}</small></div></article>)}</section>}
const SCHEDULE_DRIVE_URL='https://drive.google.com/drive/folders/139yVJOFPzcaIfSxRuaK8MI22-W5OHpxI';
export function Schedule(){return <div className="narrow"><a className="surface schedule-card" href={SCHEDULE_DRIVE_URL} target="_blank" rel="noopener noreferrer"><div className="icon-box blue"><Icon name="schedule"/></div><div><h3>Horário de Aula</h3><p>Toque para abrir a grade no Drive.</p></div><Icon name="next"/></a></div>}
export function Agenda(){const {data}=usePortal();const [filter,setFilter]=useState('Todos');const items=data?.agenda||[];const categories=['Todos',...Array.from(new Set(items.map(e=>e.category)))];const visible=items.filter(e=>filter==='Todos'||e.category===filter);return <><div className="day-tabs">{categories.map(f=><button className={filter===f?'active':''} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div><section className="surface padded">{visible.length?<EventList items={visible}/>:<Empty title="Nenhuma atividade na agenda." description="Provas, reuniões e eventos da sua turma aparecerão aqui."/>}</section></>}
export function Profile(){const {data}=usePortal();if(!data)return null;const {student}=data;return <section className="surface padded narrow profile"><div className="avatar">{student.avatarUrl?<img src={student.avatarUrl} alt=""/>:studentInitials(student.name)}</div><h2>{student.name}</h2><p>Estudante</p>{[['E-mail institucional',student.email],['Série',student.grade],['Turma',student.className],['Turno',student.shift],['Escola',student.school]].filter(([,v])=>v).map(([k,v])=><div className="profile-field" key={k}><small>{k}</small><b>{v}</b></div>)}</section>}
function studentInitials(name:string){const parts=name.trim().split(/\s+/).filter(Boolean);return ((parts[0]?.[0]||'A')+(parts.length>1?parts[parts.length-1][0]:'')).toUpperCase()}
export function More({go,logout}:{go:Navigate;logout:()=>void}){return <section className="surface narrow">{[['profile','Perfil'],['schedule','Horários'],['agenda','Agenda'],['olympics','Topo do Saber'],['notices','Informes'],['settings','Configurações'],['about','Sobre']].map(([route,title])=><button className="list-row" key={route} onClick={()=>go(route)}><b>{title}</b><Icon name="next"/></button>)}<button className="list-row danger" onClick={logout}><b>Sair</b><Icon name="logout"/></button></section>}
